### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by caesar** [nlfiedler/timedog#13]
I'm trying to update the homebrew formula for timedog, but it requires a tagged release. I realise it's a few years since timedog has been updated, but would you be able to tag the current HEAD as a release for me?

At present the latest release in homebrew is over two years older than HEAD so this would be really useful.

**Comment by nlfiedler** [comment]
Certainly, `v1.0` tag is now available, pointing to the most recent commit.

**Comment by caesar** [comment]
Thanks! That was quick!

But... looks like the [last version on Google Code](https://code.google.com/archive/p/timedog/downloads), which is the version now in Homebrew, was v1.3.
Any chance you could change this tag to v.1.4?

Thanks! 👍

**Comment by nlfiedler** [comment]
Wow, I didn't realize there was still anything left on Google Code, I thought that stuff vanished when they (mostly) shut it down. Anyway, renamed the v1.0 to v1.4 per request.

**Comment by nlfiedler** [comment]
@caesar I also pushed tags for the commits that likely match the original "1.1", "1.2", and "1.3".

**Comment by caesar** [comment]
@nlfiedler, awesome, thanks!

Yes, it always surprises me that all the Google Code stuff still exists, too... I guess most of the software on there has never been migrated anywhere else.
